development:
  adapter: "sqlite3"                  # Database vendor (soon, postgres)
  database: "db/development.sqlite3"  # File path of the database

production:
  adapter: sqlite3
  database: db/production.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
 